from pathlib import Path

from docx import Document
from docx.shared import Inches

from app.models.content import Assumption, BudgetItem, DocumentContent, Risk, TimelinePhase


def generate_document(output_path: Path, content: DocumentContent) -> Path:
    doc = Document()
    _set_margins(doc)

    _add_title_page(doc, content.title)

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(content.executive_summary)

    doc.add_heading("Project Objectives", level=1)
    _add_bullet_list(doc, content.objectives)

    doc.add_heading("Project Scope", level=1)
    _add_bullet_list(doc, content.scope)

    doc.add_heading("Assumptions", level=1)
    _add_assumptions_table(doc, content.assumptions)

    doc.add_heading("Implementation Timeline", level=1)
    _add_timeline_table(doc, content.timeline)

    doc.add_heading("Budget Breakdown", level=1)
    _add_budget_table(doc, content.budget)

    doc.add_heading("Risk Register", level=1)
    _add_risk_table(doc, content.risks)

    doc.add_heading("Success Metrics", level=1)
    _add_bullet_list(doc, content.success_metrics)

    doc.add_heading("Conclusion", level=1)
    doc.add_paragraph(content.conclusion)

    doc.save(output_path)
    return output_path


def _set_margins(doc: Document) -> None:
    for section in doc.sections:
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.85)
        section.right_margin = Inches(0.85)


def _add_title_page(doc: Document, title_text: str) -> None:
    title = doc.add_paragraph()
    title.style = doc.styles["Title"]
    title.add_run(title_text)

    subtitle = doc.add_paragraph("90-Day Launch Project Plan")
    subtitle.style = doc.styles["Subtitle"]
    doc.add_paragraph("Generated by Fluid AI")
    doc.add_page_break()


def _add_bullet_list(doc: Document, items: list[str]) -> None:
    if not items:
        doc.add_paragraph("Not provided.")
        return
    for item in items:
        doc.add_paragraph(item, style="List Bullet")


def _add_table(doc: Document, headers: list[str], rows: list[list[str]]) -> None:
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"

    for index, header in enumerate(headers):
        table.rows[0].cells[index].text = header

    for row in rows:
        cells = table.add_row().cells
        for index, value in enumerate(row):
            cells[index].text = value


def _add_assumptions_table(doc: Document, assumptions: list[Assumption]) -> None:
    if not assumptions:
        doc.add_paragraph("No explicit assumptions recorded.")
        return
    rows = [[item.field, item.value, item.rationale] for item in assumptions]
    _add_table(doc, ["Field", "Value", "Rationale"], rows)


def _add_timeline_table(doc: Document, timeline: list[TimelinePhase]) -> None:
    if not timeline:
        doc.add_paragraph("No implementation timeline provided.")
        return
    rows = [
        [
            phase.phase,
            phase.duration,
            "\n".join(phase.activities),
            "\n".join(phase.deliverables),
        ]
        for phase in timeline
    ]
    _add_table(doc, ["Phase", "Duration", "Activities", "Deliverables"], rows)


def _add_budget_table(doc: Document, budget_items: list[BudgetItem]) -> None:
    if not budget_items:
        doc.add_paragraph("No budget details provided.")
        return
    rows = [[item.category, f"${item.amount:,.0f}", item.rationale] for item in budget_items]
    _add_table(doc, ["Category", "Amount", "Rationale"], rows)


def _add_risk_table(doc: Document, risks: list[Risk]) -> None:
    if not risks:
        doc.add_paragraph("No project risks recorded.")
        return
    rows = [[risk.risk, risk.probability, risk.impact, risk.mitigation] for risk in risks]
    _add_table(doc, ["Risk", "Probability", "Impact", "Mitigation"], rows)
