from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.section import WD_SECTION
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches


def generate_document(
    output_path: Path,
    request_id: str,
    user_request: str,
    assumptions: list[dict[str, Any]],
    execution_trace: list[dict[str, Any]],
    sections: dict[str, Any],
    evaluation: dict[str, Any],
) -> Path:
    doc = Document()
    _set_margins(doc)
    _add_header_footer(doc, request_id)

    title = doc.add_paragraph()
    title.style = doc.styles["Title"]
    title.add_run("Autonomous Document Agent Report")

    subtitle = doc.add_paragraph()
    subtitle.add_run(f"Request ID: {request_id}\n")
    subtitle.add_run(f"Generated: {datetime.now(timezone.utc).isoformat()}\n")
    subtitle.add_run(f"Source request: {user_request}")

    doc.add_page_break()

    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(sections.get("executive_summary", "A document was generated from the requested plan."))

    doc.add_heading("Assumptions Made", level=1)
    _add_table(doc, ["Field", "Value", "Reason"], assumptions)

    doc.add_heading("Plan and Execution Trace", level=1)
    trace_rows = [
        {
            "task_id": item["task_id"],
            "status": item["status"],
            "tool": item["tool"],
            "result": item.get("result_preview", ""),
        }
        for item in execution_trace
    ]
    _add_table(doc, ["Task", "Status", "Tool", "Result"], trace_rows)

    doc.add_heading("Project Sections", level=1)
    for heading, body in sections.items():
        if heading == "executive_summary":
            continue
        doc.add_heading(heading.replace("_", " ").title(), level=2)
        if isinstance(body, list):
            for bullet in body:
                doc.add_paragraph(str(bullet), style="List Bullet")
        elif isinstance(body, dict):
            for key, value in body.items():
                doc.add_paragraph(f"{key}: {value}")
        else:
            doc.add_paragraph(str(body))

    doc.add_heading("Quality Evaluation", level=1)
    for key in ["completeness", "clarity", "consistency", "requirement_coverage", "passed", "score"]:
        doc.add_paragraph(f"{key}: {evaluation.get(key)}")

    doc.add_heading("Risks", level=1)
    risks = sections.get("risks", ["Timeline slip", "Budget uncertainty"])
    if isinstance(risks, list):
        for item in risks:
            doc.add_paragraph(str(item), style="List Bullet")
    else:
        doc.add_paragraph(str(risks))

    doc.add_heading("Timeline", level=1)
    timeline = sections.get("timeline", {})
    if isinstance(timeline, dict):
        for key, value in timeline.items():
            if isinstance(value, list):
                doc.add_paragraph(f"{key}:")
                for item in value:
                    doc.add_paragraph(str(item), style="List Bullet 2")
            else:
                doc.add_paragraph(f"{key}: {value}")

    doc.save(output_path)
    return output_path


def _set_margins(doc: Document) -> None:
    for section in doc.sections:
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.85)
        section.right_margin = Inches(0.85)


def _add_header_footer(doc: Document, request_id: str) -> None:
    section = doc.sections[0]
    header = section.header.paragraphs[0]
    header.text = f"Autonomous Document Agent | {request_id}"

    footer = section.footer.paragraphs[0]
    footer.text = "Generated by Autonomous Document Agent | Page "
    _add_page_number(footer)


def _add_page_number(paragraph) -> None:
    run = paragraph.add_run()
    fld_char1 = OxmlElement("w:fldChar")
    fld_char1.set(qn("w:fldCharType"), "begin")
    instr_text = OxmlElement("w:instrText")
    instr_text.set(qn("xml:space"), "preserve")
    instr_text.text = "PAGE"
    fld_char2 = OxmlElement("w:fldChar")
    fld_char2.set(qn("w:fldCharType"), "end")
    run._r.append(fld_char1)
    run._r.append(instr_text)
    run._r.append(fld_char2)


def _add_table(doc: Document, headers: list[str], rows: list[dict[str, Any]]) -> None:
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    hdr_cells = table.rows[0].cells
    for index, header in enumerate(headers):
        hdr_cells[index].text = header

    for row in rows:
        cells = table.add_row().cells
        for index, header in enumerate(headers):
            key = header.lower().replace(" ", "_")
            if key == "task":
                key = "task_id"
            cells[index].text = str(row.get(key, row.get(header, "")))
